name: mlproject-env
channels:
  - conda-forge
dependencies:
  - python=3.12.7
  - pip
  - pip:
      - mlflow==2.19.0
      - pandas==2.2.3
      - numpy==2.2.1
      - scikit-learn==1.6.0
      - matplotlib==3.10.0
